import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 1024px;
    height: 1024px;
    GridLayout {
        spacing: 5px;
        Row {
            Text {
                text: "Agent Framework";
                color: red;
            }
        }

        Row {
            TextInput {
                text: "Enter value";
            }
        }
    }
}
